# Generated by Django 4.2.8 on 2026-02-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_tenant_and_role_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_access_customers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_sales",
            field=models.BooleanField(default=True),
        ),
    ]
