# Generated by Django 4.2.8 on 2026-02-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_pan_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr/"),
        ),
    ]
